\hypertarget{classerror__already__set}{}\doxysection{error\+\_\+already\+\_\+set Class Reference}
\label{classerror__already__set}\index{error\_already\_set@{error\_already\_set}}


{\ttfamily \#include $<$pytypes.\+h$>$}

Inheritance diagram for error\+\_\+already\+\_\+set\+:\begin{figure}[H]
\begin{center}
\leavevmode
\includegraphics[height=2.000000cm]{classerror__already__set}
\end{center}
\end{figure}
\doxysubsection*{Public Member Functions}
\begin{DoxyCompactItemize}
\item 
\mbox{\hyperlink{classerror__already__set_a9f6456fb9f03460d943682037132e819}{error\+\_\+already\+\_\+set}} ()
\item 
\Hypertarget{classerror__already__set_a8bea74f30b56b414ee2629009cb252f4}\label{classerror__already__set_a8bea74f30b56b414ee2629009cb252f4} 
{\bfseries error\+\_\+already\+\_\+set} (const \mbox{\hyperlink{classerror__already__set}{error\+\_\+already\+\_\+set}} \&)=default
\item 
\Hypertarget{classerror__already__set_a77db6b6c5770db3ec72f6e522375084a}\label{classerror__already__set_a77db6b6c5770db3ec72f6e522375084a} 
{\bfseries error\+\_\+already\+\_\+set} (\mbox{\hyperlink{classerror__already__set}{error\+\_\+already\+\_\+set}} \&\&)=default
\item 
void \mbox{\hyperlink{classerror__already__set_a751b231e5c796447d867cf30007a7fc0}{restore}} ()
\item 
void \mbox{\hyperlink{classerror__already__set_a7dad9b92f8d2132d1f627ea9329c7aeb}{discard\+\_\+as\+\_\+unraisable}} (\mbox{\hyperlink{classobject}{object}} err\+\_\+context)
\item 
void \mbox{\hyperlink{classerror__already__set_ad672bc258e8d563bbfbeb7a0817d1608}{discard\+\_\+as\+\_\+unraisable}} (const char $\ast$err\+\_\+context)
\item 
\Hypertarget{classerror__already__set_a471237e45e4049e9e9ec4bc049621eb1}\label{classerror__already__set_a471237e45e4049e9e9ec4bc049621eb1} 
void {\bfseries clear} ()
\item 
bool \mbox{\hyperlink{classerror__already__set_a6585d62b1153c401745df155a7c87f6f}{matches}} (\mbox{\hyperlink{classhandle}{handle}} exc) const
\item 
\Hypertarget{classerror__already__set_a837ac3c84def45be3a018e796e7c8b28}\label{classerror__already__set_a837ac3c84def45be3a018e796e7c8b28} 
const \mbox{\hyperlink{classobject}{object}} \& {\bfseries type} () const
\item 
\Hypertarget{classerror__already__set_a8338c35feee04b20a745ac7123e2dc81}\label{classerror__already__set_a8338c35feee04b20a745ac7123e2dc81} 
const \mbox{\hyperlink{classobject}{object}} \& {\bfseries value} () const
\item 
\Hypertarget{classerror__already__set_a7df5afe2a73db865aa754f7affe751ff}\label{classerror__already__set_a7df5afe2a73db865aa754f7affe751ff} 
const \mbox{\hyperlink{classobject}{object}} \& {\bfseries trace} () const
\end{DoxyCompactItemize}


\doxysubsection{Detailed Description}
Fetch and hold an error which was already set in Python. An instance of this is typically thrown to propagate python-\/side errors back through C++ which can either be caught manually or else falls back to the function dispatcher (which then raises the captured error back to python). 

\doxysubsection{Constructor \& Destructor Documentation}
\Hypertarget{classerror__already__set_a9f6456fb9f03460d943682037132e819}\label{classerror__already__set_a9f6456fb9f03460d943682037132e819} 
\index{error\_already\_set@{error\_already\_set}!error\_already\_set@{error\_already\_set}}
\index{error\_already\_set@{error\_already\_set}!error\_already\_set@{error\_already\_set}}
\doxysubsubsection{\texorpdfstring{error\_already\_set()}{error\_already\_set()}}
{\footnotesize\ttfamily error\+\_\+already\+\_\+set\+::error\+\_\+already\+\_\+set (\begin{DoxyParamCaption}{ }\end{DoxyParamCaption})\hspace{0.3cm}{\ttfamily [inline]}}

Constructs a new exception from the current Python error indicator, if any. The current Python error indicator will be cleared. 

\doxysubsection{Member Function Documentation}
\Hypertarget{classerror__already__set_ad672bc258e8d563bbfbeb7a0817d1608}\label{classerror__already__set_ad672bc258e8d563bbfbeb7a0817d1608} 
\index{error\_already\_set@{error\_already\_set}!discard\_as\_unraisable@{discard\_as\_unraisable}}
\index{discard\_as\_unraisable@{discard\_as\_unraisable}!error\_already\_set@{error\_already\_set}}
\doxysubsubsection{\texorpdfstring{discard\_as\_unraisable()}{discard\_as\_unraisable()}\hspace{0.1cm}{\footnotesize\ttfamily [1/2]}}
{\footnotesize\ttfamily void error\+\_\+already\+\_\+set\+::discard\+\_\+as\+\_\+unraisable (\begin{DoxyParamCaption}\item[{const char $\ast$}]{err\+\_\+context }\end{DoxyParamCaption})\hspace{0.3cm}{\ttfamily [inline]}}

An alternate version of {\ttfamily \doxylink{classerror__already__set_a7dad9b92f8d2132d1f627ea9329c7aeb}{discard\+\_\+as\+\_\+unraisable()}}, where a string provides information on the location of the error. For example, {\ttfamily \+\_\+\+\_\+func\+\_\+\+\_\+} could be helpful. \Hypertarget{classerror__already__set_a7dad9b92f8d2132d1f627ea9329c7aeb}\label{classerror__already__set_a7dad9b92f8d2132d1f627ea9329c7aeb} 
\index{error\_already\_set@{error\_already\_set}!discard\_as\_unraisable@{discard\_as\_unraisable}}
\index{discard\_as\_unraisable@{discard\_as\_unraisable}!error\_already\_set@{error\_already\_set}}
\doxysubsubsection{\texorpdfstring{discard\_as\_unraisable()}{discard\_as\_unraisable()}\hspace{0.1cm}{\footnotesize\ttfamily [2/2]}}
{\footnotesize\ttfamily void error\+\_\+already\+\_\+set\+::discard\+\_\+as\+\_\+unraisable (\begin{DoxyParamCaption}\item[{\mbox{\hyperlink{classobject}{object}}}]{err\+\_\+context }\end{DoxyParamCaption})\hspace{0.3cm}{\ttfamily [inline]}}

If it is impossible to raise the currently-\/held error, such as in a destructor, we can write it out using Python\textquotesingle{}s unraisable hook ({\ttfamily sys.\+unraisablehook}). The error context should be some object whose {\ttfamily repr()} helps identify the location of the error. Python already knows the type and value of the error, so there is no need to repeat that. After this call, the current object no longer stores the error variables, and neither does Python. \Hypertarget{classerror__already__set_a6585d62b1153c401745df155a7c87f6f}\label{classerror__already__set_a6585d62b1153c401745df155a7c87f6f} 
\index{error\_already\_set@{error\_already\_set}!matches@{matches}}
\index{matches@{matches}!error\_already\_set@{error\_already\_set}}
\doxysubsubsection{\texorpdfstring{matches()}{matches()}}
{\footnotesize\ttfamily bool error\+\_\+already\+\_\+set\+::matches (\begin{DoxyParamCaption}\item[{\mbox{\hyperlink{classhandle}{handle}}}]{exc }\end{DoxyParamCaption}) const\hspace{0.3cm}{\ttfamily [inline]}}

Check if the currently trapped error type matches the given Python exception class (or a subclass thereof). May also be passed a tuple to search for any exception class matches in the given tuple. \Hypertarget{classerror__already__set_a751b231e5c796447d867cf30007a7fc0}\label{classerror__already__set_a751b231e5c796447d867cf30007a7fc0} 
\index{error\_already\_set@{error\_already\_set}!restore@{restore}}
\index{restore@{restore}!error\_already\_set@{error\_already\_set}}
\doxysubsubsection{\texorpdfstring{restore()}{restore()}}
{\footnotesize\ttfamily void error\+\_\+already\+\_\+set\+::restore (\begin{DoxyParamCaption}{ }\end{DoxyParamCaption})\hspace{0.3cm}{\ttfamily [inline]}}

Give the currently-\/held error back to Python, if any. If there is currently a Python error already set it is cleared first. After this call, the current object no longer stores the error variables (but the {\ttfamily .what()} string is still available). 

The documentation for this class was generated from the following files\+:\begin{DoxyCompactItemize}
\item 
pytypes.\+h\item 
pybind11.\+h\end{DoxyCompactItemize}
