\label{index_top}%
\Hypertarget{index_top}%
 \hypertarget{md_ext_2hera_2extern_2_catch2_2docs_2limitations_autotoc_md141}{}\doxysection{Known limitations}\label{md_ext_2hera_2extern_2_catch2_2docs_2limitations_autotoc_md141}
Over time, some limitations of Catch2 emerged. Some of these are due to implementation details that cannot be easily changed, some of these are due to lack of development resources on our part, and some of these are due to plain old 3rd party bugs.\hypertarget{md_ext_2hera_2extern_2_catch2_2docs_2limitations_autotoc_md142}{}\doxysubsection{Implementation limits}\label{md_ext_2hera_2extern_2_catch2_2docs_2limitations_autotoc_md142}
\hypertarget{md_ext_2hera_2extern_2_catch2_2docs_2limitations_autotoc_md143}{}\doxysubsubsection{Sections nested in loops}\label{md_ext_2hera_2extern_2_catch2_2docs_2limitations_autotoc_md143}
If you are using {\ttfamily SECTION}s inside loops, you have to create them with different name per loop\textquotesingle{}s iteration. The recommended way to do so is to incorporate the loop\textquotesingle{}s counter into section\textquotesingle{}s name, like so\+:


\begin{DoxyCode}{0}
\DoxyCodeLine{TEST\_CASE(\ \textcolor{stringliteral}{"{}Looped\ section"{}}\ )\ \{}
\DoxyCodeLine{\ \ \ \ \textcolor{keywordflow}{for}\ (\textcolor{keywordtype}{char}\ i\ =\ \textcolor{charliteral}{'0'};\ i\ <\ \textcolor{charliteral}{'5'};\ ++i)\ \{}
\DoxyCodeLine{\ \ \ \ \ \ \ \ SECTION(std::string(\textcolor{stringliteral}{"{}Looped\ section\ "{}})\ +\ i)\ \{}
\DoxyCodeLine{\ \ \ \ \ \ \ \ \ \ \ \ SUCCEED(\ \textcolor{stringliteral}{"{}Everything\ is\ OK"{}}\ );}
\DoxyCodeLine{\ \ \ \ \ \ \ \ \}}
\DoxyCodeLine{\ \ \ \ \}}
\DoxyCodeLine{\}}

\end{DoxyCode}


or with a {\ttfamily DYNAMIC\+\_\+\+SECTION} macro (that was made for exactly this purpose)\+:


\begin{DoxyCode}{0}
\DoxyCodeLine{TEST\_CASE(\ \textcolor{stringliteral}{"{}Looped\ section"{}}\ )\ \{}
\DoxyCodeLine{\ \ \ \ \textcolor{keywordflow}{for}\ (\textcolor{keywordtype}{char}\ i\ =\ \textcolor{charliteral}{'0'};\ i\ <\ \textcolor{charliteral}{'5'};\ ++i)\ \{}
\DoxyCodeLine{\ \ \ \ \ \ \ \ DYNAMIC\_SECTION(\ \textcolor{stringliteral}{"{}Looped\ section\ "{}}\ <<\ i)\ \{}
\DoxyCodeLine{\ \ \ \ \ \ \ \ \ \ \ \ SUCCEED(\ \textcolor{stringliteral}{"{}Everything\ is\ OK"{}}\ );}
\DoxyCodeLine{\ \ \ \ \ \ \ \ \}}
\DoxyCodeLine{\ \ \ \ \}}
\DoxyCodeLine{\}}

\end{DoxyCode}
\hypertarget{md_ext_2hera_2extern_2_catch2_2docs_2limitations_autotoc_md144}{}\doxysubsubsection{Tests might be run again if last section fails}\label{md_ext_2hera_2extern_2_catch2_2docs_2limitations_autotoc_md144}
If the last section in a test fails, it might be run again. This is because Catch2 discovers {\ttfamily SECTION}s dynamically, as they are about to run, and if the last section in test case is aborted during execution (e.\+g. via the {\ttfamily REQUIRE} family of macros), Catch2 does not know that there are no more sections in that test case and must run the test case again.\hypertarget{md_ext_2hera_2extern_2_catch2_2docs_2limitations_autotoc_md145}{}\doxysubsubsection{Min\+GW/\+Cyg\+Win compilation (linking) is extremely slow}\label{md_ext_2hera_2extern_2_catch2_2docs_2limitations_autotoc_md145}
Compiling Catch2 with Min\+GW can be exceedingly slow, especially during the linking step. As far as we can tell, this is caused by deficiencies in its default linker. If you can tell Min\+GW to instead use lld, via {\ttfamily -\/fuse-\/ld=lld}, the link time should drop down to reasonable length again.\hypertarget{md_ext_2hera_2extern_2_catch2_2docs_2limitations_autotoc_md146}{}\doxysubsection{Features}\label{md_ext_2hera_2extern_2_catch2_2docs_2limitations_autotoc_md146}
This section outlines some missing features, what is their status and their possible workarounds.\hypertarget{md_ext_2hera_2extern_2_catch2_2docs_2limitations_autotoc_md147}{}\doxysubsubsection{Thread safe assertions}\label{md_ext_2hera_2extern_2_catch2_2docs_2limitations_autotoc_md147}
Catch2\textquotesingle{}s assertion macros are not thread safe. This does not mean that you cannot use threads inside Catch\textquotesingle{}s test, but that only single thread can interact with Catch\textquotesingle{}s assertions and other macros.

This means that this is ok 
\begin{DoxyCode}{0}
\DoxyCodeLine{std::vector<std::thread>\ threads;}
\DoxyCodeLine{std::atomic<int>\ cnt\{\ 0\ \};}
\DoxyCodeLine{\textcolor{keywordflow}{for}\ (\textcolor{keywordtype}{int}\ i\ =\ 0;\ i\ <\ 4;\ ++i)\ \{}
\DoxyCodeLine{\ \ \ \ threads.emplace\_back([\&]()\ \{}
\DoxyCodeLine{\ \ \ \ \ \ \ \ ++cnt;\ ++cnt;\ ++cnt;\ ++cnt;}
\DoxyCodeLine{\ \ \ \ \});}
\DoxyCodeLine{\}}
\DoxyCodeLine{\textcolor{keywordflow}{for}\ (\textcolor{keyword}{auto}\&\ t\ :\ threads)\ \{\ t.join();\ \}}
\DoxyCodeLine{REQUIRE(cnt\ ==\ 16);}

\end{DoxyCode}
 because only one thread passes the {\ttfamily REQUIRE} macro and this is not 
\begin{DoxyCode}{0}
\DoxyCodeLine{std::vector<std::thread>\ threads;}
\DoxyCodeLine{std::atomic<int>\ cnt\{\ 0\ \};}
\DoxyCodeLine{\textcolor{keywordflow}{for}\ (\textcolor{keywordtype}{int}\ i\ =\ 0;\ i\ <\ 4;\ ++i)\ \{}
\DoxyCodeLine{\ \ \ \ threads.emplace\_back([\&]()\ \{}
\DoxyCodeLine{\ \ \ \ \ \ \ \ ++cnt;\ ++cnt;\ ++cnt;\ ++cnt;}
\DoxyCodeLine{\ \ \ \ \ \ \ \ CHECK(cnt\ ==\ 16);}
\DoxyCodeLine{\ \ \ \ \});}
\DoxyCodeLine{\}}
\DoxyCodeLine{\textcolor{keywordflow}{for}\ (\textcolor{keyword}{auto}\&\ t\ :\ threads)\ \{\ t.join();\ \}}
\DoxyCodeLine{REQUIRE(cnt\ ==\ 16);}

\end{DoxyCode}


Because C++11 provides the necessary tools to do this, we are planning to remove this limitation in the future.\hypertarget{md_ext_2hera_2extern_2_catch2_2docs_2limitations_autotoc_md148}{}\doxysubsubsection{Process isolation in a test}\label{md_ext_2hera_2extern_2_catch2_2docs_2limitations_autotoc_md148}
Catch does not support running tests in isolated (forked) processes. While this might in the future, the fact that Windows does not support forking and only allows full-\/on process creation and the desire to keep code as similar as possible across platforms, mean that this is likely to take significant development time, that is not currently available.\hypertarget{md_ext_2hera_2extern_2_catch2_2docs_2limitations_autotoc_md149}{}\doxysubsubsection{Running multiple tests in parallel}\label{md_ext_2hera_2extern_2_catch2_2docs_2limitations_autotoc_md149}
Catch2 keeps test execution in one process strictly serial, and there are no plans to change this. If you find yourself with a test suite that takes too long to run and yo uwant to make it parallel, you have to run multiple processes side by side.

There are 2 basic ways to do that,
\begin{DoxyItemize}
\item you can split your tests into multiple binaries, and run those binaries in parallel
\item you can run the same test binary multiple times, but run a different subset of the tests in each process
\end{DoxyItemize}

There are multiple ways to achieve the latter, the easiest way is to use \href{command-line.md\#test-sharding}{\texttt{ test sharding}}.\hypertarget{md_ext_2hera_2extern_2_catch2_2docs_2limitations_autotoc_md150}{}\doxysubsection{3rd party bugs}\label{md_ext_2hera_2extern_2_catch2_2docs_2limitations_autotoc_md150}
This section outlines known bugs in 3rd party components (this means compilers, standard libraries, standard runtimes).\hypertarget{md_ext_2hera_2extern_2_catch2_2docs_2limitations_autotoc_md151}{}\doxysubsubsection{Visual Studio 2017 – raw string literal in assert fails to compile}\label{md_ext_2hera_2extern_2_catch2_2docs_2limitations_autotoc_md151}
There is a known bug in Visual Studio 2017 (VC 15), that causes compilation error when preprocessor attempts to stringize a raw string literal ({\ttfamily \#} preprocessor directive is applied to it). This snippet is sufficient to trigger the compilation error\+:


\begin{DoxyCode}{0}
\DoxyCodeLine{\textcolor{preprocessor}{\#include\ <catch2/catch\_test\_macros.hpp>}}
\DoxyCodeLine{}
\DoxyCodeLine{TEST\_CASE(\textcolor{stringliteral}{"{}test"{}})\ \{}
\DoxyCodeLine{\ \ \ \ CHECK(std::string(R\textcolor{stringliteral}{"{}("{}\(\backslash\))"{})\ ==\ }\textcolor{stringliteral}{"{}\(\backslash\)"{}\(\backslash\)\(\backslash\)"{}});}
\DoxyCodeLine{\}}

\end{DoxyCode}


Catch2 provides a workaround, by letting the user disable stringification of the original expression by defining {\ttfamily CATCH\+\_\+\+CONFIG\+\_\+\+DISABLE\+\_\+\+STRINGIFICATION}, like so\+: 
\begin{DoxyCode}{0}
\DoxyCodeLine{\textcolor{preprocessor}{\#define\ CATCH\_CONFIG\_DISABLE\_STRINGIFICATION}}
\DoxyCodeLine{\textcolor{preprocessor}{\#include\ <catch2/catch\_test\_macros.hpp>}}
\DoxyCodeLine{}
\DoxyCodeLine{TEST\_CASE(\textcolor{stringliteral}{"{}test"{}})\ \{}
\DoxyCodeLine{\ \ \ \ CHECK(std::string(R\textcolor{stringliteral}{"{}("{}\(\backslash\))"{})\ ==\ }\textcolor{stringliteral}{"{}\(\backslash\)"{}\(\backslash\)\(\backslash\)"{}});}
\DoxyCodeLine{\}}

\end{DoxyCode}


{\itshape Do note that this changes the output\+:} 
\begin{DoxyCode}{0}
\DoxyCodeLine{catchwork\(\backslash\)test1.cpp(6):}
\DoxyCodeLine{PASSED:}
\DoxyCodeLine{\ \ CHECK(\ Disabled\ by\ CATCH\_CONFIG\_DISABLE\_STRINGIFICATION\ )}
\DoxyCodeLine{with\ expansion:}
\DoxyCodeLine{\ \ "{}"{}\(\backslash\)"{}\ ==\ "{}"{}\(\backslash\)"{}}

\end{DoxyCode}
\hypertarget{md_ext_2hera_2extern_2_catch2_2docs_2limitations_autotoc_md152}{}\doxysubsubsection{Clang/\+G++ – skipping leaf sections after an exception}\label{md_ext_2hera_2extern_2_catch2_2docs_2limitations_autotoc_md152}
Some versions of {\ttfamily libc++} and {\ttfamily libstdc++} (or their runtimes) have a bug with {\ttfamily std\+::uncaught\+\_\+exception()} getting stuck returning {\ttfamily true} after rethrow, even if there are no active exceptions. One such case is this snippet, which skipped the sections \char`\"{}a\char`\"{} and \char`\"{}b\char`\"{}, when compiled against {\ttfamily libcxxrt} from master 
\begin{DoxyCode}{0}
\DoxyCodeLine{\textcolor{preprocessor}{\#include\ <catch2/catch\_test\_macros.hpp>}}
\DoxyCodeLine{}
\DoxyCodeLine{TEST\_CASE(\textcolor{stringliteral}{"{}a"{}})\ \{}
\DoxyCodeLine{\ \ \ \ CHECK\_THROWS(\textcolor{keywordflow}{throw}\ 3);}
\DoxyCodeLine{\}}
\DoxyCodeLine{}
\DoxyCodeLine{TEST\_CASE(\textcolor{stringliteral}{"{}b"{}})\ \{}
\DoxyCodeLine{\ \ \ \ \textcolor{keywordtype}{int}\ i\ =\ 0;}
\DoxyCodeLine{\ \ \ \ SECTION(\textcolor{stringliteral}{"{}a"{}})\ \{\ i\ =\ 1;\ \}}
\DoxyCodeLine{\ \ \ \ SECTION(\textcolor{stringliteral}{"{}b"{}})\ \{\ i\ =\ 2;\ \}}
\DoxyCodeLine{\ \ \ \ CHECK(i\ >\ 0);}
\DoxyCodeLine{\}}

\end{DoxyCode}


If you are seeing a problem like this, i.\+e. a weird test paths that trigger only under Clang with {\ttfamily libc++}, or only under very specific version of {\ttfamily libstdc++}, it is very likely you are seeing this. The only known workaround is to use a fixed version of your standard library.\hypertarget{md_ext_2hera_2extern_2_catch2_2docs_2limitations_autotoc_md153}{}\doxysubsubsection{libstdc++, $<$tt$>$\+\_\+\+GLIBCXX\+\_\+\+DEBUG$<$/tt$>$ macro and random ordering of tests}\label{md_ext_2hera_2extern_2_catch2_2docs_2limitations_autotoc_md153}
Running a Catch2 binary compiled against libstdc++ with {\ttfamily \+\_\+\+GLIBCXX\+\_\+\+DEBUG} macro defined with {\ttfamily -\/-\/order rand} will cause a debug check to trigger and abort the run due to self-\/assignment. \href{https://stackoverflow.com/questions/22915325/avoiding-self-assignment-in-stdshuffle/23691322}{\texttt{ This is a known bug inside libstdc++}}

Workaround\+: Don\textquotesingle{}t use {\ttfamily -\/-\/order rand} when compiling against debug-\/enabled libstdc++. 